### PR TITLE
fix: update version, and fix DecoratedPlatformTextfield

### PR DESCRIPTION
**Pull request by Kiruel**
- update version of `flutter_platform_widgets`
- fix `DecoratedPlatformTextfield`

### CODE REVIEW

**Comment by Kiruel** [comment]
Hi @robert-virkus, can you take a look please.

Thanks,

**Review by robert-virkus — APPROVED** [review]
Many thanks!

**Comment by Kiruel** [comment]
Can you bundle a new version please @robert-virkus ?

**Comment by robert-virkus** [comment]
Thanks again - I released the Flutter 3.16+ version 1.0.0 now!

**Pull request merged**
